(function(global){"use strict";
const uuid=()=>global.crypto?.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const lista=()=>obtenerUnidades();
const folio=()=>`RTAB-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${String(lista().filter(u=>u.folioTablet).length+1).padStart(4,"0")}`;
const liberarTablet=(activoId,unidadClave)=>{if(!activoId)return;const activos=obtenerActivos(),i=activos.findIndex(a=>a.id===activoId);if(i>=0&&activos[i].asignadoUnidad===unidadClave){activos[i]={...activos[i],estado:"Disponible",responsable:"",asignadoUnidad:"",actualizadoEn:new Date().toISOString()};guardarActivos(activos);}};
const asignarTablet=(activoId,unidadClave)=>{if(!activoId)return;const activos=obtenerActivos(),i=activos.findIndex(a=>a.id===activoId&&a.categoria==="Tablet"&&(a.estado==="Disponible"||a.asignadoUnidad===unidadClave));if(i<0)throw new Error("La tablet seleccionada ya no está disponible.");activos[i]={...activos[i],estado:"Asignado",responsable:`Unidad ${unidadClave}`,asignadoUnidad:unidadClave,empleadoId:"",actualizadoEn:new Date().toISOString()};guardarActivos(activos);};
global.UnidadesCRUD={
listar(){return lista().map(x=>({...x}));},obtener(id){return lista().find(x=>x.id===id)||null;},
guardar(d){const unidades=lista(),anterior=unidades.find(x=>x.id===d.id),numero=String(d.numero||"").replace(/\D/g,"").padStart(3,"0"),clave=`${d.tipo}-${numero}`,tabletCambio=(anterior?.tabletActivoId||"")!==(d.tabletActivoId||"");if(!numero||!/^\d+$/.test(String(d.numero)))throw new Error("El número de unidad debe contener solo dígitos.");if(unidades.some(x=>x.clave===clave&&x.id!==d.id))throw new Error(`La unidad ${clave} ya existe.`);if(unidades.some(x=>x.serieGPS===d.serieGPS.toUpperCase()&&x.id!==d.id))throw new Error("El número de serie del GPS ya está registrado.");if(d.tipo!=="TR"&&d.tabletActivoId)throw new Error("Las tablets solo pueden vincularse a unidades TR.");if(d.tabletActivoId&&!d.operador.trim())throw new Error("Captura el operador responsable de la tablet.");if(d.tabletActivoId&&tabletCambio&&!d.firmaTablet)throw new Error("La firma responsiva del operador es obligatoria.");const ahora=new Date().toISOString(),ubicacion=d.latitud!==""&&d.longitud!==""?{latitud:Number(d.latitud),longitud:Number(d.longitud),fecha:ahora}:null;if(ubicacion&&(ubicacion.latitud>90||ubicacion.latitud< -90||ubicacion.longitud>180||ubicacion.longitud< -180))throw new Error("Las coordenadas GPS no son válidas.");if(tabletCambio)liberarTablet(anterior?.tabletActivoId,anterior?.clave);asignarTablet(d.tabletActivoId,clave);const tablet=d.tabletActivoId?obtenerActivos().find(a=>a.id===d.tabletActivoId):null,nuevaResponsiva=d.tabletActivoId&&tabletCambio;const registro={id:d.id||uuid(),tipo:d.tipo,numero,clave,placas:d.placas.toUpperCase(),serieGPS:d.serieGPS.toUpperCase(),operador:d.operador,estado:d.estado,tabletActivoId:d.tipo==="TR"?(d.tabletActivoId||""):"",tablet:tablet?{activo:tablet.activo,serie:tablet.serie}:null,firmaTablet:nuevaResponsiva?d.firmaTablet:(d.tabletActivoId?anterior?.firmaTablet||"":""),folioTablet:nuevaResponsiva?folio():(d.tabletActivoId?anterior?.folioTablet||"":""),fechaAsignacionTablet:nuevaResponsiva?ahora.slice(0,10):(d.tabletActivoId?anterior?.fechaAsignacionTablet||"":""),ubicacion,notas:d.notas,creadoEn:anterior?.creadoEn||ahora,actualizadoEn:ahora};const i=unidades.findIndex(x=>x.id===registro.id);if(i<0)unidades.unshift(registro);else unidades[i]=registro;guardarUnidades(unidades);registrarMovimiento(d.id?"Actualización de unidad":"Alta de unidad",`${d.id?"Se actualizó":"Se registró"} la unidad ${clave}`);if(nuevaResponsiva)registrarMovimiento("Responsiva de tablet",`Se firmó ${registro.folioTablet} para la tablet ${tablet.activo} asignada a ${clave}`);return registro;},
eliminar(id){const unidades=lista(),u=unidades.find(x=>x.id===id);if(!u)return false;liberarTablet(u.tabletActivoId,u.clave);guardarUnidades(unidades.filter(x=>x.id!==id));registrarMovimiento("Baja de unidad",`Se eliminó la unidad ${u.clave}`);return true;}
};})(window);
