(function(global){"use strict";
const uuid=()=>global.crypto?.randomUUID?global.crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const folio=()=>"RESP-"+new Date().toISOString().slice(0,10).replaceAll("-","")+"-"+String(obtenerAsignaciones().length+1).padStart(4,"0");
global.AsignacionesCRUD={
 listar(){return obtenerAsignaciones().map(x=>({...x}));},obtener(id){return this.listar().find(x=>x.id===id)||null;},
 crear(d){const activos=obtenerActivos(),tipo=d.tipoDestino||"Empleado",esUnidad=tipo==="UnidadTR",empleados=obtenerEmpleados(),unidades=obtenerUnidades();let destino,empleado=null,unidad=null;
  if(esUnidad){unidad=unidades.find(u=>u.id===d.unidadId&&u.tipo==="TR"&&u.estado==="Activa");if(!unidad)throw new Error("Selecciona una unidad TR activa.");if(d.activoIds.length!==1)throw new Error("Selecciona una sola tablet para la unidad TR.");}
  else{empleado=empleados.find(e=>e.id===d.empleadoId&&e.estatus==="Activo");if(!empleado)throw new Error("Selecciona un empleado activo.");}
  const seleccionados=activos.filter(a=>d.activoIds.includes(a.id)&&a.estado==="Disponible");if(!seleccionados.length||seleccionados.length!==d.activoIds.length)throw new Error("Uno de los equipos ya no está disponible.");if(esUnidad&&seleccionados.some(a=>a.categoria!=="Tablet"))throw new Error("A una unidad TR solo se puede asignar una tablet.");if(esUnidad&&unidad.tabletActivoId)throw new Error(`La unidad ${unidad.clave} ya tiene una tablet asignada.`);if(!d.firmaEmpleado)throw new Error("La firma digital de conformidad es obligatoria.");
  const ahora=new Date().toISOString(),nombre=esUnidad?`Unidad ${unidad.clave}`:[empleado.nombres,empleado.apellidos].filter(Boolean).join(" ");destino=esUnidad?{tipo:"UnidadTR",id:unidad.id,nombre,clave:unidad.clave,operador:unidad.operador||"",placas:unidad.placas||"",serieGPS:unidad.serieGPS||""}:{tipo:"Empleado",id:empleado.id,nombre,numeroEmpleado:empleado.numeroEmpleado,departamento:empleado.departamento,puesto:empleado.puesto,empresa:empleado.empresa};
  const registro={id:uuid(),folio:folio(),tipoDestino:tipo,destino,empleadoId:empleado?.id||"",unidadId:unidad?.id||"",empleado:esUnidad?{nombre}:destino,fechaAsignacion:d.fechaAsignacion,fechaDevolucion:"",estado:"Activa",entregaPor:d.entregaPor,observaciones:d.observaciones,firmaEmpleado:d.firmaEmpleado,creadoEn:ahora,activos:seleccionados.map(a=>({id:a.id,activo:a.activo,serie:a.serie,marca:a.marca,modelo:a.modelo,categoria:a.categoria}))};
  const lista=obtenerAsignaciones();lista.unshift(registro);guardarAsignaciones(lista);const revision=new Date(d.fechaAsignacion+"T12:00:00Z"),meses=Number(global.obtenerConfiguracion?.().mesesMantenimiento)||6;revision.setUTCMonth(revision.getUTCMonth()+meses);const proximoMantenimiento=revision.toISOString().slice(0,10);
  seleccionados.forEach(s=>{const i=activos.findIndex(a=>a.id===s.id);activos[i]={...activos[i],estado:"Asignado",empleadoId:empleado?.id||"",asignadoUnidad:unidad?.clave||"",responsable:nombre,proximoMantenimiento,actualizadoEn:ahora};});guardarActivos(activos);
  if(esUnidad){const i=unidades.findIndex(u=>u.id===unidad.id);unidades[i]={...unidades[i],tabletActivoId:seleccionados[0].id,tablet:{activo:seleccionados[0].activo,serie:seleccionados[0].serie},firmaTablet:d.firmaEmpleado,folioTablet:registro.folio,fechaAsignacionTablet:d.fechaAsignacion,actualizadoEn:ahora};guardarUnidades(unidades);}
  registrarMovimiento("Asignación",`Se asignaron ${seleccionados.length} activo(s) a ${nombre}. Folio ${registro.folio}`);return registro;
 },
 devolver(id){const lista=obtenerAsignaciones(),i=lista.findIndex(a=>a.id===id);if(i<0||lista[i].estado!=="Activa")return false;const r=lista[i],activos=obtenerActivos(),ahora=new Date().toISOString();r.estado="Devuelta";r.fechaDevolucion=ahora.slice(0,10);r.actualizadoEn=ahora;r.activos.forEach(e=>{const x=activos.findIndex(a=>a.id===e.id);if(x>=0&&(activos[x].empleadoId===r.empleadoId||activos[x].asignadoUnidad===r.destino?.clave))activos[x]={...activos[x],estado:"Disponible",empleadoId:"",asignadoUnidad:"",responsable:"",actualizadoEn:ahora};});guardarActivos(activos);if(r.tipoDestino==="UnidadTR"){const unidades=obtenerUnidades(),u=unidades.findIndex(x=>x.id===r.unidadId);if(u>=0&&r.activos.some(a=>a.id===unidades[u].tabletActivoId)){unidades[u]={...unidades[u],tabletActivoId:"",tablet:null,firmaTablet:"",folioTablet:"",fechaAsignacionTablet:"",actualizadoEn:ahora};guardarUnidades(unidades);}}guardarAsignaciones(lista);registrarMovimiento("Devolución",`Se devolvieron los equipos del folio ${r.folio}`);return true;},
 eliminarHistorial(id){const lista=obtenerAsignaciones(),r=lista.find(a=>a.id===id);if(!r||r.estado!=="Devuelta")return false;guardarAsignaciones(lista.filter(a=>a.id!==id));registrarMovimiento("Depuración",`Se eliminó el historial devuelto ${r.folio}`);return true;}
};})(window);
