(function(global){"use strict";
const uuid=()=>global.crypto?.randomUUID?global.crypto.randomUUID():"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,c=>{const r=Math.random()*16|0;return(c==="x"?r:r&3|8).toString(16);});
const folio=()=>"MANT-"+new Date().toISOString().slice(0,10).replaceAll("-","")+"-"+String(obtenerMantenimientos().length+1).padStart(4,"0");
const seisMeses=fecha=>{const d=new Date(fecha+"T12:00:00Z"),meses=Number(global.obtenerConfiguracion?.().mesesMantenimiento)||6;d.setUTCMonth(d.getUTCMonth()+meses);return d.toISOString().slice(0,10);};
global.MantenimientoCRUD={
 listar(){return obtenerMantenimientos().map(x=>({...x}));},obtener(id){return this.listar().find(x=>x.id===id)||null;},
 crear(d){const activos=obtenerActivos(),i=activos.findIndex(a=>a.id===d.activoId&&a.estado!=="Baja"&&a.estado!=="Reparación");if(i<0)throw new Error("El activo no está disponible para mantenimiento.");const a=activos[i],ahora=new Date().toISOString();const registro={id:uuid(),folio:folio(),activoId:a.id,activo:{activo:a.activo,serie:a.serie,marca:a.marca,modelo:a.modelo,categoria:a.categoria},estadoAnterior:a.estado,empleadoIdAnterior:a.empleadoId||"",responsableAnterior:a.responsable||"",tipo:d.tipo,falla:d.falla,diagnostico:d.diagnostico,proveedor:d.proveedor,tecnico:d.tecnico,fechaEntrada:d.fechaEntrada,fechaEstimada:d.fechaEstimada,costo:Number(d.costo)||0,estado:"En reparación",fechaSalida:"",resultado:"",temporizador:{iniciadoEn:ahora,acumuladoMs:0,corriendo:true,finalizadoMs:0},creadoEn:ahora};const lista=obtenerMantenimientos();lista.unshift(registro);guardarMantenimientos(lista);activos[i]={...a,estado:"Reparación",actualizadoEn:ahora};guardarActivos(activos);registrarMovimiento("Mantenimiento",`El activo ${a.activo} ingresó a ${d.tipo}. Folio ${registro.folio}`);return registro;},
 cerrar(id,d){const lista=obtenerMantenimientos(),i=lista.findIndex(x=>x.id===id&&x.estado==="En reparación");if(i<0)throw new Error("El servicio ya no está activo.");if(!d.firmaConformidad)throw new Error("La firma de conformidad es obligatoria.");const r=lista[i],activos=obtenerActivos(),j=activos.findIndex(a=>a.id===r.activoId),ahora=new Date().toISOString();const timer=r.temporizador||{iniciadoEn:r.creadoEn,acumuladoMs:0,corriendo:true};const transcurrido=timer.corriendo&&timer.iniciadoEn?Date.now()-new Date(timer.iniciadoEn).getTime():0;const total=(timer.acumuladoMs||0)+Math.max(0,transcurrido);r.temporizador={...timer,acumuladoMs:total,corriendo:false,detenidoEn:ahora,finalizadoMs:total};r.estado="Terminado";r.resultado=d.resultado;r.fechaSalida=d.fechaSalida;r.costo=Number(d.costo)||0;r.recibeNombre=d.recibeNombre;r.firmaConformidad=d.firmaConformidad;r.proximoMantenimiento=seisMeses(d.fechaSalida);r.actualizadoEn=ahora;if(j>=0){const estado=r.empleadoIdAnterior?"Asignado":"Disponible";activos[j]={...activos[j],estado,empleadoId:r.empleadoIdAnterior,responsable:r.responsableAnterior,ultimoMantenimiento:d.fechaSalida,proximoMantenimiento:r.proximoMantenimiento,actualizadoEn:ahora};guardarActivos(activos);}guardarMantenimientos(lista);registrarMovimiento("Mantenimiento terminado",`Finalizó el servicio ${r.folio} del activo ${r.activo.activo}. Tiempo técnico ${Math.round(total/60000)} min.`);return r;},
 eliminar(id){const lista=obtenerMantenimientos(),r=lista.find(x=>x.id===id);if(!r||r.estado!=="Terminado")return false;guardarMantenimientos(lista.filter(x=>x.id!==id));return true;},seisMeses
};})(window);
